name: 'InfluxDB Action'
description: 'Install and configure InfluxDB and the InfluxDB CLI.'
inputs:
  influxdb-version:
    description: 'The version of InfluxDB to install.'
    required: false
    default: 'nightly'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/setup.sh
      shell: bash