name: 'InfluxDB Action'
description: 'Install and configure InfluxDB and the InfluxDB CLI.'
inputs:
  influxdb-org:
    description: 'The initial Organization of the InfluxDB instance.'
    required: false
    default: 'organization'
  influxdb-user:
    description: 'The initial User of the InfluxDB instance.'
    required: false
    default: 'user'
  influxdb-pass:
    description: 'The initial Password of the InfluxDB instance.'
    required: false
    default: 'password'
  influxdb-bucket:
    description: 'The initial Bucket of the InfluxDB instance.'
    required: false
    default: 'bucket'
runs:
  using: "composite"
  steps:
    - name: Download and Install InfluxDB
      run: ${{ github.action_path }}/install-influxdb.sh
      shell: bash
    - name: Configure InfluxDB
      run: ${{ github.action_path }}/setup-influxdb.sh
      shell: bash